### TEST GET / WEBSITE
GET http://localhost:8383


### TEST GET / dashboard WEBSITE
GET http://localhost:8383/dashboard

### TEST GET / DATA ENDPOINT
GET http://localhost:8383/api/data

### TEST GET / DATA ENDPOINT FOR ADDING A USER
POST http://localhost:8383/api/data
Content-Type: application/json

{
  "name": "Hehee"
}